resilience4j:
  circuitbreaker:
    configs:
      ml-circuit:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permit-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      products:
        base-config: ml-circuit
  timelimiter:
    configs:
      ml-circuit:
        timeout-duration: 2s
    instances:
      products:
        base-config: ml-circuit
spring:
  cloud:
    gateway:
      routes:
        - id: items-service
          uri: lb://items-service
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=2
            - AddRequestHeader=token-request,itemTokenRequest
            - AddResponseHeader=response-token-response,itemTokenResponse
            - AddRequestParameter=name,hector
        - id: products-service
          uri: lb://products-service
          predicates:
            - Path=/api/products/**
            - Header= token, \d+
            - Method=GET, POST, PUT, DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: products
                statusCodes: 500
                fallbackUri: forward:/api/items/list
            - StripPrefix=2
            - name: CookiesFilter
              args:
                message: Hola es mi mensaje personalizado
                cookieName: User
                cookieValue: hcejag
